# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a434177efd4d701b28fee0833918ef2a20a356741388f1319d6f24d0d44dc18d151855b9630e6335bb40f7f811ed78e3b767b9f0165023625dd8717450a49fe

test:
  secret_key_base: 38811f6d04e96e44f9ebc7c0934979975622c97db913f29da2cf68acb10600b447131a0d6be230db827614b28ea7f65b757244ef5f1331bcf3415eddc3325952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
